### ISSUE TITLE
phoenix database error

### ISSUE THREAD

**Issue by MyraBaba** [jaigouk/storm_wiki#14]
streamlit run storm.py --server.port 8509 --server.address 0.0.0.0

WARNING: Static file serving is enabled, but no static folder found at /home/bc/Projects/ODS/stormv2/storm_wiki/static. To disable static file serving, set server.enableStaticServing to false.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8509

phoenix.config : INFO     : 📋 Ensuring phoenix working directory: /home/bc/.phoenix
phoenix.inferences.inferences : INFO     : Dataset: phoenix_inferences_9addac4d-19e0-4a4a-8014-7da43f3bcdd7 initialized
2024-08-06 17:49:43.036 Uncaught app exception
Traceback (most recent call last):
  File "/home/bc/Projects/ODS/stormv2/venvStormv2/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/home/bc/Projects/ODS/stormv2/storm_wiki/storm.py", line 9, in <module>
    from pages_util.CreateNewArticle import create_new_article_page
  File "/home/bc/Projects/ODS/stormv2/storm_wiki/pages_util/CreateNewArticle.py", line 19, in <module>
    categories = FileIOHelper.load_categories()
  File "/home/bc/Projects/ODS/stormv2/storm_wiki/util/file_io.py", line 48, in load_categories
    c.execute("SELECT value FROM settings WHERE key='categories'")
sqlite3.OperationalError: no such table: settings

**Comment by jaigouk** [comment]
yeah. i need to make it as optional. i will create a fix for that.

**Comment by jaigouk** [comment]
fixed with https://github.com/jaigouk/storm_wiki/commit/0db26333a9fe81078e2aeab81c82c4f2d6ddf8e0
